Repository colcon/colcon.readthedocs.org, pull requests merged in 2018-04, with the labels that each got.

#1 base-paths --> --paths
  developer/bootstrap.rst
Labels: bug

#2 add missing cd to source instructions
  developer/bootstrap.rst
Labels: bug

#6 add travis to try build and spell check
  .travis.yml
  conf.py
Labels: enhancement, review

#5 add documentation for configuration files
  index.rst
  spelling_wordlist.txt
  user/configuration.rst
Labels: review

#3 update naming of --package* arguments
  migration/ament_tools.rst
  migration/catkin_make_isolated.rst
  migration/catkin_tools.rst
  user/quick-start.rst
Labels: enhancement, review

#7 remove escaped leading space example since it doesn't work on Windows
  migration/ament_tools.rst
  migration/catkin_make_isolated.rst
  migration/catkin_tools.rst
Labels: bug, review

#8 recommend adding a keyword to the metadata
  developer/contribution.rst
Labels: review
